/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PairSymbol = IDL.Text;
export const ForexPair = IDL.Record({
  'ask' : IDL.Float64,
  'bid' : IDL.Float64,
  'isUp' : IDL.Bool,
  'changePercent' : IDL.Float64,
  'symbol' : PairSymbol,
});

export const idlService = IDL.Service({
  '__pairs' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(ForexPair)],
      ['query'],
    ),
  'addPair' : IDL.Func([IDL.Text], [], []),
  'getPairs' : IDL.Func([], [IDL.Vec(ForexPair)], ['query']),
  'removePair' : IDL.Func([IDL.Text], [], []),
  'updatePrices' : IDL.Func([IDL.Vec(ForexPair)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PairSymbol = IDL.Text;
  const ForexPair = IDL.Record({
    'ask' : IDL.Float64,
    'bid' : IDL.Float64,
    'isUp' : IDL.Bool,
    'changePercent' : IDL.Float64,
    'symbol' : PairSymbol,
  });
  
  return IDL.Service({
    '__pairs' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(ForexPair)],
        ['query'],
      ),
    'addPair' : IDL.Func([IDL.Text], [], []),
    'getPairs' : IDL.Func([], [IDL.Vec(ForexPair)], ['query']),
    'removePair' : IDL.Func([IDL.Text], [], []),
    'updatePrices' : IDL.Func([IDL.Vec(ForexPair)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };