/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ForexPair {
  'ask' : number,
  'bid' : number,
  'isUp' : boolean,
  'changePercent' : number,
  'symbol' : PairSymbol,
}
export type PairSymbol = string;
export interface _SERVICE {
  '__pairs' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<ForexPair>>,
  'addPair' : ActorMethod<[string], undefined>,
  'getPairs' : ActorMethod<[], Array<ForexPair>>,
  'removePair' : ActorMethod<[string], undefined>,
  'updatePrices' : ActorMethod<[Array<ForexPair>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];